services:
  development:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm start
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    networks:
      network:
        aliases:
          - postgres-net
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      network:
        aliases:
          - postgres-net

volumes:
  docker-nest-postgres:

networks:
  network:
    driver: bridge
